<?xml version="1.0" encoding="utf-8"?>
<!-- This file contains project properties used by the build. -->
<Project>
	<PropertyGroup>
		<BeatSaberDir>D:\BSManager\BSInstances\1.45.1</BeatSaberDir>
		<GameDirectory>$(BeatSaberDir)</GameDirectory>
		<CopyPDB>false</CopyPDB>
		<DisableCopyToGame>false</DisableCopyToGame>
		<ImportBSMTTargets>True</ImportBSMTTargets>
		<BSMTProjectType>BSIPA</BSMTProjectType>
	</PropertyGroup>
</Project>
